# Generated by Django 5.2 on 2025-04-23 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='rentalrequest',
            name='start_date',
        ),
    ]
